spring:
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    #    password: r#3vl8v@ZMtws       # 密码（默认为空）
    timeout: 5000  # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
      test-on-create: false #
      test-on-return: false #
      test-on-borrow: true #在空闲时检查有效性
      test-while-idle: true #在获取连接的时候检查有效

  freemarker:
    #    allow-request-override: false  #req访问request
    check-template-location: true  #req访问request
    expose-spring-macro-helpers: true  #req访问request
    expose-request-attributes: true  #req访问request
    expose-session-attributes: true  #req访问request
    request-context-attribute: request  #req访问request
    #    request-context-attribute: request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      template_update_delay: 0      #页面缓存
    number_format: '0.##'   #数字格式化，无小数

    # slf4j日志配置
  logging:
    # 配置级别
    level:
      #分包配置级别，即不同的目录下可以使用不同的级别
      com.icloud: INFO
      root: INFO
      org.springframework.web: DEBUG
#sharding:
#  jdbc:
#    datasource:
#      names: ds0,ds1
#      ds0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://gz-cdb-o77g5le8.sql.tencentcdb.com:63194/ldscdb?useUnicode=true&characterEncoding=utf-8
#        username: ldsctest
#        password: nnyr2018
#      ds1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://gz-cdb-o77g5le8.sql.tencentcdb.com:63194/haiyun_pay_test?useUnicode=true&characterEncoding=utf-8
#        username: haiyun_pay_test
#        password: nnyr2019
#    config:
#      sharding:
#        props:
#          sql.show: true
#        tables:
#          t_scanactivity_user_scanrecord:  #t_scanactivity_user_scanrecord表
#            key-generator-column-name: id  #主键
#            actual-data-nodes: ds${0..1}.t_scanactivity_user_scanrecord_{0..5}  #数据节点
#            database-strategy:  #分库策略
#              inline:
#                sharding-column: userid
#                algorithm-expression: ds${userid % 2}
#            table-strategy:  #分表策略
#              inline:
#                shardingColumn: userid
#                algorithm-expression: t_scanactivity_user_scanrecord_${userid % 6}
#
